# Generated by Django 5.1.4 on 2024-12-06 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("empleados", "0002_mensaje_alter_area_nombre_alter_cargo_nombre_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mensaje",
            name="asunto",
        ),
        migrations.RemoveField(
            model_name="mensaje",
            name="email",
        ),
        migrations.RemoveField(
            model_name="mensaje",
            name="nombre",
        ),
    ]
