# Generated by Django 5.1.4 on 2024-12-06 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("empleados", "0003_remove_mensaje_asunto_remove_mensaje_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="empleado",
            name="activo",
        ),
    ]
