# Generated by Django 5.1.4 on 2024-12-07 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empleados", "0005_ciudad_region_alter_empleado_area_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empleado",
            name="ciudad",
            field=models.CharField(
                choices=[
                    ("Arica", "Arica"),
                    ("Iquique", "Iquique"),
                    ("Antofagasta", "Antofagasta"),
                    ("Copiapó", "Copiapó"),
                    ("La Serena", "La Serena"),
                    ("Valparaíso", "Valparaíso"),
                    ("Santiago", "Santiago"),
                    ("Talca", "Talca"),
                    ("Chillán", "Chillán"),
                    ("Concepción", "Concepción"),
                    ("Temuco", "Temuco"),
                    ("Valdivia", "Valdivia"),
                    ("Puerto Montt", "Puerto Montt"),
                    ("Coyhaique", "Coyhaique"),
                    ("Punta Arenas", "Punta Arenas"),
                ],
                db_index=True,
                default="Santiago",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="region",
            field=models.CharField(
                choices=[
                    ("Región de Arica y Parinacota", "Región de Arica y Parinacota"),
                    ("Región de Tarapacá", "Región de Tarapacá"),
                    ("Región de Antofagasta", "Región de Antofagasta"),
                    ("Región de Atacama", "Región de Atacama"),
                    ("Región de Coquimbo", "Región de Coquimbo"),
                    ("Región de Valparaíso", "Región de Valparaíso"),
                    (
                        "Región Metropolitana de Santiago",
                        "Región Metropolitana de Santiago",
                    ),
                    ("Región del Maule", "Región del Maule"),
                    ("Región de Ñuble", "Región de Ñuble"),
                    ("Región del Biobío", "Región del Biobío"),
                    ("Región de La Araucanía", "Región de La Araucanía"),
                    ("Región de Los Ríos", "Región de Los Ríos"),
                    ("Región de Los Lagos", "Región de Los Lagos"),
                    ("Región de Aysén", "Región de Aysén"),
                    (
                        "Región de Magallanes y de la Antártica Chilena",
                        "Región de Magallanes y de la Antártica Chilena",
                    ),
                ],
                db_index=True,
                default="Región Metropolitana de Santiago",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="area",
            field=models.ForeignKey(
                choices=[
                    ("Administrativa", "Administrativa"),
                    ("Operativa", "Operativa"),
                    ("Comercial", "Comercial"),
                ],
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="empleados",
                to="empleados.area",
            ),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="cargo",
            field=models.ForeignKey(
                choices=[
                    ("Analista", "Analista"),
                    ("Supervisor", "Supervisor"),
                    ("Gerente", "Gerente"),
                    ("Asistente", "Asistente"),
                ],
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="empleados",
                to="empleados.cargo",
            ),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="departamento",
            field=models.ForeignKey(
                choices=[
                    ("Recursos Humanos", "Recursos Humanos"),
                    ("Finanzas", "Finanzas"),
                    ("Operaciones", "Operaciones"),
                    ("TI", "Tecnologías de la Información"),
                ],
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="empleados",
                to="empleados.departamento",
            ),
        ),
        migrations.DeleteModel(
            name="Ciudad",
        ),
        migrations.DeleteModel(
            name="Region",
        ),
    ]
