# Generated by Django 5.1.4 on 2024-12-07 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empleados", "0009_alter_area_nombre_alter_cargo_nombre_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="area",
            constraint=models.UniqueConstraint(
                fields=("nombre", "departamento"), name="unique_area_departamento"
            ),
        ),
    ]
