# Generated by Django 5.1.4 on 2024-12-07 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empleados", "0010_area_unique_area_departamento"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="area",
            name="unique_area_departamento",
        ),
        migrations.RemoveField(
            model_name="area",
            name="departamento",
        ),
        migrations.AddField(
            model_name="area",
            name="departamentos",
            field=models.ManyToManyField(
                related_name="areas", to="empleados.departamento"
            ),
        ),
    ]
