# Generated by Django 5.1.2 on 2024-10-28 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empleado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_completo", models.CharField(max_length=100)),
                ("rut", models.CharField(max_length=12, unique=True)),
                (
                    "sexo",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Femenino")], max_length=1
                    ),
                ),
                ("direccion", models.CharField(max_length=255)),
                ("telefono", models.CharField(max_length=20)),
                ("cargo", models.CharField(max_length=50)),
                ("fecha_ingreso", models.DateField()),
                ("area", models.CharField(max_length=50)),
                ("departamento", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="ContactoEmergencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_contacto", models.CharField(max_length=100)),
                ("relacion", models.CharField(max_length=50)),
                ("telefono_contacto", models.CharField(max_length=20)),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contactos_emergencia",
                        to="empleados.empleado",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CargaFamiliar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_carga", models.CharField(max_length=100)),
                ("parentesco", models.CharField(max_length=50)),
                (
                    "sexo",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Femenino")], max_length=1
                    ),
                ),
                ("rut_carga", models.CharField(max_length=12)),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cargas_familiares",
                        to="empleados.empleado",
                    ),
                ),
            ],
        ),
    ]
