# Generated by Django 5.1.2 on 2024-10-28 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("empleados", "0002_customuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="customuser",
        ),
    ]
